language: java

jdk:
- openjdk11

install: travis_wait 10

# notifications:
#   slack:
#     secure: rXEJoGb/7AIhEGdDe2PoLl1DyeMYz8E1hyXxM6Qpxnw+v27zTTrNKifSkEtO3YGzPttp/xS1VtwgTA3fkzLxoPd04dy8jDkBaYFiIH1zjzeaoQzM0JIKXmcHVM+/3/RjhrjyyxCy8sGpjI9YUaw4R71edDueDqlPn0U+5B41qwSKiGqAj0/EbGuk1AcI4fXbDEwWHR6JVdV+1RiIWSFmKF8P1UmLHn3hWC3Hej4gNT0LQ7gdQbKKrRY3VgasuC7TTmnNlToswrEfyXVye37/+XeYi+nZJARzVpYcB6ImTQujxJX8f+EVazVpSShrQZSmyQ4JIprWpkv8+05ogHeTvDahPcfUXZfY2BEcQ8Q+X0ShQNlx022n6+pkAo2RR4/0+EmFjtVVdIgFY9IZo9CnjBkNQLKJtp81oYWdpwAMCA00aJm+3dTHFHLC0qxcFFLhCUyRiHq0iYrRtx+lEGY6hlUr+s7MIvzHA0gOwYYqY6Wf6dd+Z+XgO5jMY73e0odEkEziIBBI3ocQbw9ooRr+WuYPJ5eeC5nRgUUNUhQ1PRnkX+/QjU16bxeTIDNI41TmPcqQM0R4g3fB63aJrET+76H1O5uYPp4+Ex8S0t0Kg93t1PXAAiWT1UpRKvqGVFkvbjn20sbenI0V/s0zfpjYS4l8tn90D+5WfAK817tPbUY=
